server:
  port: 8081

spring:
  application:
    name: user

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a8dc33a7-07f7-420f-901e-79f09136ed05
      config:
        server-addr: 127.0.0.1:8848
        namespace: a8dc33a7-07f7-420f-901e-79f09136ed05
    loadbalancer:
      enabled: true

  config:
    import:
      - nacos:application.yml?group=dev
      - nacos:datasource.yml?group=dev
      - nacos:dynamictp.yml?group=dev

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5s

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  circuitbreaker:
    enabled: true

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    # This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
    # For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
    register-mode: instance
  protocol:
    name: tri
    port: 50053
  application:
    name: UserApplication
    logger: slf4j
    protocol: tri
    qos-port: 22224