server:
  port: 8080

spring:
  application:
    name: user

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.7:8848
        namespace: a8dc33a7-07f7-420f-901e-79f09136ed05
      config:
        server-addr: 192.168.3.7:8848
        namespace: a8dc33a7-07f7-420f-901e-79f09136ed05
    loadbalancer:
      enabled: true

  config:
    import:
      - nacos:application.yml?group=user

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  circuitbreaker:
    enabled: true