server:
  port: 9090

spring:
  application:
    name: order

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a8dc33a7-07f7-420f-901e-79f09136ed05
      config:
        server-addr: 127.0.0.1:8848
        namespace: a8dc33a7-07f7-420f-901e-79f09136ed05

  config:
    import:
      - nacos:application.yml?group=dev
      - nacos:dynamictp.yml?group=dev

  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:nacos:shardingsphere.yaml?serverAddr=127.0.0.1:8848&namespace=a8dc33a7-07f7-420f-901e-79f09136ed05&group=dev

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    # This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
    # For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
    register-mode: instance
  protocol:
    name: tri
    port: 50052
  application:
    name: OrderApplication
    logger: slf4j
    protocol: tri
    qos-port: 22223