server:
  port: 6010

spring:
  application:
    name: inventory

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.7:8848
        namespace: a8dc33a7-07f7-420f-901e-79f09136ed05
      config:
        server-addr: 192.168.3.7:8848
        namespace: a8dc33a7-07f7-420f-901e-79f09136ed05

  config:
    import:
      - nacos:common.yml?group=dev
      - nacos:datasource.yml?group=dev
      - nacos:mybatis.yml?group=dev
      - nacos:redisson.yml?group=dev
      - nacos:rocketmq.yml?group=dev

dubbo:
  registry:
    address: nacos://192.168.3.7:8848
    # This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
    # For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
    register-mode: instance
  protocol:
    name: tri
    port: 50051
  application:
    name: InventoryApplication
    logger: slf4j
    protocol: tri
    qos-port: 22222